config/routes.rb
Debateable::Application.routes.draw do
  resources :users, :only => [:index, :create, :destroy, :new, :edit, :show, :update] do
    resources :propositions, :only => [:index, :create, :destroy, :new, :edit, :show] 
    resources :oppositions
  end

  resources :propositions
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/help',        to: 'static_pages#help'
  match '/about',       to: 'static_pages#about'
  match '/signup',      to: 'users#new'
  match '/signin',      to: 'sessions#new'
  match '/signout',     to: 'sessions#destroy', via: :delete
  match '/debateable-propositions', to: 'propositions#debateable_propositions'

end

app/models/debate.rb
class Debate < ActiveRecord::Base
  attr_accessible :title, :proposition_attributes, :opposition_attributes

end

app/models/opposition.rb
class Opposition < ActiveRecord::Base
  attr_accessible :footnotes, :response, :slide, :title

  belongs_to :user
  belongs_to :proposition
end

app/models/proposition.rb
class Proposition < ActiveRecord::Base
  attr_accessible :footnotes, :response, :slide, :title

  belongs_to :user
  has_one :opposition
  validates :user_id, presence: true
  validates :title, presence: true

  def self.debateable_by(user)
    where do
      (user_id != user.id)
    end
  end
  # This method creates a debate and
  # Assigns its id to the instance's 
  # debate_id
  def index_on_debate
    @debate = self.build_debate(title: self.title)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessible :email, :name, :password, :password_confirmation, :id
  has_secure_password
  
  has_many :oppositions
  has_many :propositions

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :email, presence:   true, 
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }  
  validates :name, presence: true, length: { maximum: 49 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

    private

      def create_remember_token
        self.remember_token = SecureRandom.urlsafe_base64
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController

  def index
  end

  def new
    @debate = current_user.government_debate.new
  end

  def create
    @debate = current_user.government_debate.build(params[:user])
    if @debate.save
    flash[:success] = "Debate created!"
    else
    flash[:error] = "Debate not created."
    end
  end

end

app/controllers/propositions_controller.rb
class PropositionsController < ApplicationController
#  before_filter :signed_in_user
#  before_filter :correct_user, only: :destroy

  def index
    @propositions = Proposition.paginate(page: params[:page])
    if !signed_in?
      flash[:alert] = "You may browse current debates, but you should sign up to start debating!"
    end
  end

  def debateable_propositions
    @propositions = Proposition.debateable_by(current_user)
  end

  def show
    @proposition = Proposition.find(params[:id])
    if !signed_in?
      flash[:alert] = "Sign Up or Sign In to oppose this proposition."
    end
  end

  def new
    @proposition = current_user.propositions.new(params[:proposition])
  end

  def create
    @user = current_user
    @proposition = current_user.propositions.create(params[:proposition])
    if @proposition.save 
      flash[:success] = "Proposition saved!"
      redirect_to @user
    else
      flash[:error] = "Proposition not saved."
    end
  end

  private
    def correct_user
      @proposition = current_user.propositions.find_by_id(params[:id])
      redirect_to root_path if @proposition.nil
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
    flash.now[:error] = 'Invalid email/password combo'  
    render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]  
  before_filter :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @propositions_count = @user.propositions.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome, debater!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def start_debate
  end

  private

    def signed_in_user
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Debateable"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/propositions_helper.rb
module PropositionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/debates/new.html.erb
<% provide (:title, 'Create a Debate') %>
<h1>Set the topic:</h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://keppy.github.com"><i class="icon-eye-open"></i> by james dominguez</a>
  </small>
  <nav>
    <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Help",  help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
     <a class="brand" href='/'>
       Debateable
     </a>
     <form class="navbar-search pull-right">
       <input type="text" class="search-query" placeholder="Search">
     </form>
     <nav>
         <ul class="nav pull-right">
           <li><%= link_to "Home",    root_path %></li>
           <li><%= link_to "Help",    help_path %></li>
           <li><%= link_to "About",   about_path %></li>
           <% if signed_in? %>
             <li id="menu" class="dropdown">
               <a href="#menu" class="dropdown-toggle" data-toggle="dropdown">
             Account<b class="caret"></b>
             </a>
             <ul class="dropdown-menu">
               <li><%= link_to "Profile", current_user %></li>
               <li><%= link_to "Settings", edit_user_path(current_user) %></li>
               <li class="divider"></li>
               <li>
                 <%= link_to "Sign out", signout_path, method: "delete" %>
               </li>
             </ul>
           </li>
         <% else %>
           <li><%= link_to "Sign in", signin_path %></li>
         <% end %>
       </ul>
     </nav>
    </div>
  </div>
</header>
     

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%=value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/propositions/_proposition.html.erb
<li>
  <%= link_to proposition.title, proposition %>
</li>

app/views/propositions/debateable_proposition_index.html.erb
<% provide(:title, 'Debateable Propositions') %>
<h1>Debateable Propositions</h1>

<%= will_paginate %>

<ul class="propositions">
  <% @propositions.each do |proposition| %>
    <%= render proposition %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/propositions/debateable_propositions.html.erb
<% provide(:title, 'Debateable Propositions') %>
<h1>Debateable Propositions</h1>


<ul class="propositions">
  <% @propositions.each do |proposition| %>
    <%= render proposition %>
  <% end %>
</ul>

app/views/propositions/index.html.erb
<% provide(:title, 'Debateable Propositions') %>
<h1>Debateable Propositions</h1>

<%= will_paginate %>

<ul class="propositions">
  <% @propositions.each do |proposition| %>
    <%= render proposition %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/propositions/new.html.erb
<% provide(:title, 'Create a Proposition') %>
<% @proposition = current_user.propositions.new if @proposition.nil? %>
<h1>Proposition</h1>

<div class="row">
    <div class="span2 offset1">
        <%= form_for @proposition, :url => { :action => "create" } do |f| %>
      <%= f.label :topic %>
      <%= f.text_field :title %>

      <%= f.label :slide %>
      <%= f.text_field :slide %>

      <%= f.label :footnotes %>
      <%= f.text_field :footnotes %>
      
      <%= f.submit "Save Proposition", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/propositions/show.html.erb
<% provide(:title, @proposition.title) %>
<h1><%= @proposition.title %></h1>

<div class = "proposition_slide">
  <slide>
    <%= @proposition.slide %>
  </slide>
</div>
<%= @proposition.footnotes %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About debateable</h1>
<p>About debateable</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Debateable Help</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Debateable,</h1>
  <h2>
    Slideshare powered debate on the web--ending flamewars, uncited statistics, and non-existent research.
  </h2>

  <%= link_to "Register now", 'signup', class: "btn btn-large btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update profile</h1>

<div class="row">
  <div class="span4 offset4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span4 offset4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %> 
      <%= f.label :name %>
      <%= f.text_field :name %>
 
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create User", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>
  <div class="center hero-unit">
    <%= link_to "Create a Proposition", new_user_proposition_path(@user), class: "btn btn-small btn-primary" %>
    <%= link_to "Oppose a Proposition", "/debateable-propositions", class: "btn btn-small btn-primary" %>
  </div>
  <div class="span8">
    <h3>Propositions <%= @propositions_count %></h3>
      <ul class="propositions">
        <% @user.propositions.each do |proposition| %>
          <%= render proposition %>
        <% end %>
      </ul>
  </div>